version: "3.9"

services:

  database:
    image: postgres:13.2-alpine
    container_name: database
    env_file: .env
    ports:
      - 5435:5432
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d/